theme: minima

title: Pepino Data
author: Pepino
email: micorreo@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Descripci√≥n del sitio

# social links
twitter_username: sin twitter # DO NOT include the @ character, or else the build will fail!
github_username:  de momento no # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
